version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./scripts/database_setup.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      # Necessary so that MySQL doesn't complain about uninitialized root user.
      # Our setup script initializes a root password on the first launch.
      # The MySQL password should be changed by hand to whatever the prod
      # credentials are as soon as possible, and then service credentials must
      # be also updated accordingly.
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  groot-api-gateway:
    build: groot-api-gateway
    ports:
      - "8000:8000"
    volumes: 
      - groot_api_gateway_volume:/var/groot-api-gateway/
    restart: always

  groot-credits-service:
    build: groot-credits-service
    ports:
      - "8765:8765"
    depends_on:
      - db
      - groot-api-gateway
    restart: always

  groot-desktop-frontend:
    build: groot-desktop-frontend
    depends_on:
      - groot-api-gateway
    ports:
      - "5000:5000"
    restart: always

  groot-events-service:
    build: groot-events-service
    ports:
      - "8002:8002"
    depends_on:
      - groot-api-gateway
    restart: always
    environment:
      TZ: "America/Chicago"

  groot-gigs-service:
    build: groot-gigs-service
    ports:
      - "8964:8964"
    depends_on:
      - db
      - groot-api-gateway
    restart: always

  groot-groups-service:
    build: groot-groups-service
    ports:
      - "9001:9001"
    depends_on:
      - groot-api-gateway
    restart: always

  groot-meme-service:
    build: groot-meme-service
    ports:
      - "42069:42069"
    depends_on:
      - db
      - groot-api-gateway
    restart: always

  groot-merch-service:
    build: groot-merch-service
    ports:
      - "6969:6969"
    depends_on:
      - db
      - groot-api-gateway
    restart: always
    environment:
      RACK_ENV: "production"

  groot-quotes-service:
    build: groot-quotes-service
    ports:
      - "9494:9494"
    depends_on:
      - db
      - groot-api-gateway
    restart: always
    environment:
      RACK_ENV: "production"

  groot-recruiters-service:
    build: groot-recruiters-service
    ports:
      - "4567:4567"
    depends_on:
      - db
      - groot-api-gateway
    restart: always
    environment:
      RACK_ENV: "production"

  groot-users-service:
    build: groot-users-service
    ports:
      - "8001:8001"
    depends_on:
      - db
      - groot-api-gateway
    restart: always
    environment:
      RACK_ENV: "production"

  groot-voz:
    build: groot-voz
    ports:
      - "5652:5652"
    depends_on:
      - db
      - groot-api-gateway
    restart: always

volumes:
    db_data:
    groot_api_gateway_volume:
