version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./scripts/database_setup.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  groot-api-gateway:
    build: groot-api-gateway
    ports:
      - "8000:8000"
    volumes:
      - groot_api_gateway_volume:/var/groot-api-gateway/
    command: ["./build/groot-api-gateway", "-u"]
    restart: always

  groot-auth-stub-service:
    build: groot-auth-stub-service
    ports:
      - "8008:8008"
    volumes:
      - ./groot-auth-stub-service:/usr/src/app
    restart: always

  groot-credits-service:
    build: groot-credits-service
    ports:
      - "8765:8765"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-credits-service:/usr/src/app
    environment:
      CREDITS_DEBUG: "True"
    restart: always

  groot-desktop-frontend:
    build: groot-desktop-frontend
    depends_on:
      - groot-api-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./groot-desktop-frontend:/usr/src/app
    restart: always

  groot-events-service:
    build: groot-events-service
    ports:
      - "8002:8002"
    depends_on:
      - groot-api-gateway
    volumes:
      - ./groot-events-service:/usr/src/app
    restart: always

  groot-gigs-service:
    build: groot-gigs-service
    ports:
      - "8964:8964"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-gigs-service:/usr/src/app
    environment:
      GIG_DEBUG: "True"
    restart: always

  groot-groups-service:
    build: groot-groups-service
    ports:
      - "9001:9001"
    depends_on:
      - groot-api-gateway
    volumes:
      - ./groot-groups-service:/usr/src/app
    restart: always

  groot-meme-service:
    build: groot-meme-service
    ports:
      - "42069:42069"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-meme-service:/usr/src/app
    environment:
      MEME_DEBUG: "True"
    restart: always

  groot-merch-service:
    build: groot-merch-service
    ports:
      - "6969:6969"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-merch-service:/usr/src/app
    restart: always

  groot-quotes-service:
    build: groot-quotes-service
    ports:
      - "9494:9494"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-quotes-service:/usr/src/app
    restart: always

  groot-recruiters-service:
    build: groot-recruiters-service
    ports:
      - "4567:4567"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-recruiters-service:/usr/src/app
    restart: always

  groot-users-service:
    build: groot-users-service
    ports:
      - "8001:8001"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-users-service:/usr/src/app
    restart: always

  groot-voz:
    build: groot-voz
    ports:
      - "5652:5652"
    depends_on:
      - db
      - groot-api-gateway
    volumes:
      - ./groot-voz:/usr/src/app
    environment:
      VOZ_DEBUG: "True"
    restart: always

volumes:
    db_data:
    groot_api_gateway_volume:
