version: '2'
services:
 db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306
 groot:
   build: .
   command: /bin/bash -c "./docker/groot_setup.sh && ./dev_spinup.sh"
   working_dir: /groot-deploy
   volumes:
     - .:/groot-deploy
   ports:
     - "8000:8000"
     - "5000:5000"
   depends_on:
     - db
