version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - 3306

  groot-desktop-frontend:
    build: groot-desktop-frontend
    depends_on:
      - groot-events-service
      - groot-users-service
      - groot-groups-service
    ports:
      - "5000:5000"

  groot-events-service:
    build: groot-events-service
    ports:
      - "8002:8002"

  groot-groups-service:
    build: groot-events-service
    ports:
      - "9001:9001"

  groot-users-service:
    build: groot-users-service
    ports:
      - "8001:8001"
    depends_on:
      - db
