version: '2'
services:
 db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306
 groot:
   build: .
   command: ./dev_spinup.sh
   volumes:
     - .:/groot-deploy
   ports:
     - "8000:8000"
     - "5000:5000"
   depends_on:
     - db